# Name: turtleWrite
# Number of Parameters: 2
# Parameters: turtle - Turtle Object; letter - string (letter to print)
# What it does: Draws the given letter
# Returns: None
def turtleWrite(turtle, letter):
  if letter == "A" or letter == "a":
    writeA(turtle)
  elif letter == "B" or letter == "b":
    writeB(turtle)
  elif letter == "C" or letter == "c":
    writeC(turtle)
  elif letter == "D" or letter == "d":
    writeD(turtle)
  elif letter == "E" or letter == "e":
    writeE(turtle)
  elif letter == "F" or letter == "f":
    writeF(turtle)
  elif letter == "G" or letter == "g":
    writeG(turtle)
  elif letter == "H" or letter == "h":
    writeH(turtle)
  elif letter == "I" or letter == "i":
    writeI(turtle)
  elif letter == "J" or letter == "j":
    writeJ(turtle)
  elif letter == "K" or letter == "k":
    writeK(turtle)
  elif letter == "L" or letter == "l":
    writeL(turtle)
  elif letter == "M" or letter == "m":
    writeM(turtle)
  elif letter == "N" or letter == "n":
    writeN(turtle)
  elif letter == "O" or letter == "o":
    writeO(turtle)
  elif letter == "P" or letter == "p":
    writeP(turtle)
  elif letter == "Q" or letter == "q":
    writeQ(turtle)
  elif letter == "R" or letter == "r":
    writeR(turtle)
  elif letter == "S" or letter == "s":
    writeS(turtle)
  elif letter == "T" or letter == "t":
    writeT(turtle)
  elif letter == "U" or letter == "u":
    writeU(turtle)
  elif letter == "V" or letter == "v":
    writeV(turtle)
  elif letter == "W" or letter == "w":
    writeW(turtle)
  elif letter == "X" or letter == "x":
    writeX(turtle)
  elif letter == "Y" or letter == "y":
    writeY(turtle)
  elif letter == "Z" or letter == "z":
    writeZ(turtle)
  goNext(turtle)

def goNext(turtle):
  turtle.penup()
  turtle.fd(60)

def writeA(turtle):
  turtle.penup()
  turtle.fd(50)
  turtle.pendown()
  turtle.left(90)
  turtle.fd(75)
  turtle.circle(25,180)
  turtle.fd(25)
  turtle.left(90)
  turtle.fd(50)
  turtle.backward(50)
  turtle.right(90)
  turtle.fd(50)
  turtle.left(90)

def writeB(turtle):
  turtle.pendown()
  turtle.left(90)
  turtle.fd(100)
  turtle.backward(100)
  turtle.right(90)
  turtle.fd(25)
  turtle.circle(25,180)
  turtle.fd(25)
  turtle.right(180)
  turtle.fd(15)
  turtle.circle(25,180)
  turtle.fd(15)
  turtle.right(90)
  turtle.backward(100)
  turtle.right(90)

def writeC(turtle):
  turtle.penup()
  turtle.left(90)
  turtle.fd(25)
  turtle.right(180)
  turtle.pendown()
  turtle.circle(25,180)
  turtle.penup()
  turtle.fd(50)
  turtle.pendown()
  turtle.circle(25,180)
  turtle.fd(50)
  turtle.penup()
  turtle.fd(25)
  turtle.left(90)

def writeD(turtle):
  turtle.pendown()
  turtle.fd(25)
  turtle.circle(25,90)
  turtle.fd(50)
  turtle.circle(25,90)
  turtle.fd(25)
  turtle.left(90)
  turtle.fd(100)
  turtle.left(90)

def writeE(turtle):
  turtle.pendown()
  turtle.fd(50)
  turtle.backward(50)
  turtle.left(90)
  turtle.fd(50)
  turtle.right(90)
  turtle.fd(35)
  turtle.backward(35)
  turtle.left(90)
  turtle.fd(50)
  turtle.right(90)
  turtle.fd(50)
  turtle.backward(50)
  turtle.right(90)
  turtle.fd(100)
  turtle.left(90)

def writeF(turtle):
  turtle.pendown()
  turtle.left(90)
  turtle.fd(50)
  turtle.right(90)
  turtle.fd(35)
  turtle.backward(35)
  turtle.left(90)
  turtle.fd(50)
  turtle.right(90)
  turtle.fd(50)
  turtle.backward(50)
  turtle.right(90)
  turtle.fd(100)
  turtle.left(90)

def writeG(turtle):
  turtle.penup()
  turtle.left(90)
  turtle.fd(25)
  turtle.right(180)
  turtle.pendown()
  turtle.circle(25,180)
  turtle.fd(15)
  turtle.backward(40)
  turtle.fd(40)
  turtle.left(90)
  turtle.fd(25)
  turtle.backward(25)
  turtle.right(90)
  turtle.penup()
  turtle.fd(35)
  turtle.pendown()
  turtle.circle(25,180)
  turtle.fd(50)
  turtle.penup()
  turtle.fd(25)
  turtle.left(90)

def writeH(turtle):
  turtle.pendown()
  turtle.left(90)
  turtle.fd(100)
  turtle.backward(50)
  turtle.right(90)
  turtle.fd(50)
  turtle.left(90)
  turtle.fd(50)
  turtle.backward(100)
  turtle.penup()
  turtle.right(90)
  turtle.backward(50)

def writeI(turtle):
  turtle.pendown()
  turtle.fd(50)
  turtle.backward(25)
  turtle.left(90)
  turtle.fd(100)
  turtle.left(90)
  turtle.backward(25)
  turtle.fd(50)
  turtle.penup()
  turtle.left(90)
  turtle.fd(100)
  turtle.left(90)

def writeJ(turtle):
  turtle.penup()
  turtle.left(90)
  turtle.fd(25)
  turtle.right(180)
  turtle.pendown()
  turtle.circle(25,180)
  turtle.fd(75)
  turtle.left(90)
  turtle.fd(35)
  turtle.penup()
  turtle.fd(15)
  turtle.left(90)
  turtle.fd(100)
  turtle.left(90)

def writeK(turtle):
  turtle.pendown()
  turtle.left(90)
  turtle.fd(100)
  turtle.backward(50)
  turtle.right(90)
  turtle.circle(50,90)
  turtle.penup()
  turtle.backward(100)
  turtle.pendown()
  turtle.circle(50,90)
  turtle.left(90)
  turtle.fd(50)
  turtle.left(90)

def writeL(turtle):
  turtle.pendown()
  turtle.left(90)
  turtle.fd(100)
  turtle.backward(100)
  turtle.right(90)
  turtle.fd(50)
  turtle.backward(50)

def writeM(turtle):
  turtle.pendown()
  turtle.left(90)
  turtle.fd(100)
  turtle.penup()
  turtle.left(90)
  turtle.backward(50)
  turtle.pendown()
  turtle.right(90)
  turtle.backward(100)
  turtle.fd(100)
  turtle.left(90)
  turtle.circle(25,90)
  turtle.fd(25)
  turtle.right(180)
  turtle.fd(25)
  turtle.circle(25,90)
  turtle.left(90)
  turtle.fd(100)
  turtle.left(90)

def writeN(turtle):
  turtle.pendown()
  turtle.left(90)
  turtle.fd(100)
  turtle.penup()
  turtle.backward(100)
  turtle.right(90)
  turtle.fd(50)
  turtle.left(90)
  turtle.pendown()
  turtle.fd(100)
  turtle.penup()
  turtle.backward(25)
  turtle.left(90)
  turtle.fd(25)
  turtle.right(90)
  turtle.pendown()
  turtle.circle(25,90)
  turtle.penup()
  turtle.backward(25)
  turtle.left(90)
  turtle.fd(25)
  turtle.pendown()
  turtle.fd(50)
  turtle.circle(25,90)
  turtle.penup()
  turtle.backward(50)

def writeO(turtle):
  turtle.penup()
  turtle.left(90)
  turtle.fd(25)
  turtle.right(180)
  turtle.pendown()
  turtle.circle(25,180)
  turtle.fd(50)
  turtle.circle(25,180)
  turtle.fd(50)
  turtle.penup()
  turtle.fd(25)
  turtle.left(90)

def writeP(turtle):
  turtle.pendown()
  turtle.left(90)
  turtle.fd(50)
  turtle.right(90)
  turtle.fd(25)
  turtle.circle(25,180)
  turtle.fd(25)
  turtle.left(90)
  turtle.fd(100)
  turtle.left(90)

def writeQ(turtle):
  turtle.penup()
  turtle.left(90)
  turtle.fd(25)
  turtle.right(180)
  turtle.pendown()
  turtle.circle(25,180)
  turtle.penup()
  turtle.left(90)
  turtle.fd(25)
  turtle.left(90)
  turtle.pendown()
  turtle.circle(25,90)
  turtle.penup()
  turtle.left(90)
  turtle.fd(25)
  turtle.pendown()
  turtle.fd(50)
  turtle.circle(25,180)
  turtle.fd(50)
  turtle.penup()
  turtle.fd(25)
  turtle.left(90)

def writeR(turtle):
  turtle.pendown()
  turtle.left(90)
  turtle.fd(50)
  turtle.right(90)
  turtle.fd(25)
  turtle.circle(25,180)
  turtle.fd(25)
  turtle.left(90)
  turtle.fd(50)
  turtle.left(90)
  turtle.fd(25)
  turtle.penup()
  turtle.fd(25)
  turtle.right(90)
  turtle.fd(50)
  turtle.left(180)
  turtle.pendown()
  turtle.fd(25)
  turtle.circle(25,90)
  turtle.penup()
  turtle.fd(25)
  turtle.left(90)
  turtle.fd(50)
  turtle.left(90)

def writeS(turtle):
  turtle.penup()
  turtle.left(90)
  turtle.fd(25)
  turtle.right(180)
  turtle.pendown()
  turtle.circle(25,270)
  turtle.penup()
  turtle.backward(25)
  turtle.right(90)
  turtle.fd(25)
  turtle.pendown()
  turtle.circle(25,270)
  turtle.penup()
  turtle.backward(25)
  turtle.right(90)
  turtle.fd(50)
  turtle.left(90)

def writeT(turtle):
  turtle.penup()
  turtle.fd(25)
  turtle.left(90)
  turtle.pendown()
  turtle.fd(100)
  turtle.left(90)
  turtle.backward(25)
  turtle.fd(50)
  turtle.penup()
  turtle.left(90)
  turtle.fd(100)
  turtle.left(90)
  

def writeU(turtle):
  turtle.penup()
  turtle.left(90)
  turtle.fd(25)
  turtle.right(180)
  turtle.pendown()
  turtle.circle(25,180)
  turtle.backward(25)
  turtle.fd(100)
  turtle.penup()
  turtle.left(90)
  turtle.fd(50)
  turtle.pendown()
  turtle.left(90)
  turtle.fd(75)
  turtle.penup()
  turtle.fd(25)
  turtle.left(90)

def writeV(turtle):
  turtle.penup()
  turtle.fd(25)
  turtle.left(90)
  turtle.pendown()
  turtle.circle(25,90)
  turtle.right(90)
  turtle.fd(75)
  turtle.penup()
  turtle.right(90)
  turtle.fd(50)
  turtle.right(90)
  turtle.pendown()
  turtle.fd(75)
  turtle.right(90)
  turtle.circle(25,90)
  turtle.penup()
  turtle.right(90)
  turtle.fd(25)
  turtle.right(180)

def writeW(turtle):
  turtle.pendown()
  turtle.circle(25,90)
  turtle.fd(25)
  turtle.right(180)
  turtle.fd(25)
  turtle.circle(25,90)
  turtle.left(90)
  turtle.fd(100)
  turtle.penup()
  turtle.left(90)
  turtle.fd(50)
  turtle.left(90)
  turtle.pendown()
  turtle.fd(100)
  turtle.left(90)

def writeX(turtle):
  turtle.penup()
  turtle.fd(50)
  turtle.left(90)
  turtle.pendown()
  turtle.fd(25)
  turtle.circle(25,180)
  turtle.fd(25)
  turtle.penup()
  turtle.backward(100)
  turtle.pendown()
  turtle.fd(25)
  turtle.circle(25,180)
  turtle.fd(25)
  turtle.penup()
  turtle.left(90)
  turtle.fd(50)
  turtle.left(90)
  turtle.fd(100)
  turtle.left(90)

def writeY(turtle):
  turtle.penup()
  turtle.left(90)
  turtle.fd(25)
  turtle.right(180)
  turtle.pendown()
  turtle.circle(25,180)
  turtle.fd(75)
  turtle.penup()
  turtle.left(90)
  turtle.fd(50)
  turtle.left(90)
  turtle.pendown()
  turtle.fd(25)
  turtle.circle(25,180)
  turtle.penup()
  turtle.left(90)
  turtle.fd(50)
  turtle.left(90)
  turtle.fd(75)
  turtle.left(90)

def writeZ(turtle):
  turtle.pendown()
  turtle.fd(50)
  turtle.backward(50)
  turtle.circle(25,90)
  turtle.fd(50)
  turtle.penup()
  turtle.fd(25)
  turtle.left(90)
  turtle.pendown()
  turtle.fd(25)
  turtle.backward(50)
  turtle.circle(25,90)
  turtle.penup()
  turtle.fd(75)
  turtle.right(90)
  turtle.fd(25)
  turtle.right(180)
